server:
   port: 8090
  
spring:
   datasource:
      url: jdbc:mysql://localhost:3306/class_local_db
      username: root
      password: 2167
   jpa:
      properties:
         hibernate:
            show_sql: false
            format_sql: false
      database-platform: org.hibernate.dialect.MySQLDialect